version: '2'
services:
  web:
    image: apap-registry.cs.ui.ac.id/zidan.kharisma/apap-tk-059-web
    restart: always
    container_name: tk-059-web
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - app.env
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network

  api:
    image: apap-registry.cs.ui.ac.id/zidan.kharisma/apap-tk-059-api
    restart: always
    container_name: tk-059-api
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - app.env
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: mariadb:10.4.24
    restart: always
    container_name: tk-059-db
    env_file:
      - app.env
    volumes:
      - mysql-db-volume:/var/lib/mysql
    networks:
      - backend-network
  
  nginx:
    image: apap-registry.cs.ui.ac.id/zidan.kharisma/apap-tk-059-nginx
    container_name: tk-059-nginx
    restart: unless-stopped
    depends_on:
      - web
      - api
    ports:
      - 10059:8080
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    networks:
      - backend-network

volumes:
  mysql-db-volume:

networks:
  frontend-network:
    driver: bridge
  backend-network:
